name: Test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: DeLaGuardo/setup-clj-kondo@v1
        with:
          version: '2020.05.09'

      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.469'

      - uses: actions/checkout@v1

      - name: Cache dependencies lint
        run: echo "$(clj-kondo --lint \"$(clojure -Spath -A:provided:dev:http-drivers:test)\")"

      - name: Run linter
        run: clj-kondo --lint src test

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.469'

      - uses: actions/checkout@v1

      - name: Run format checker
        run: ./script/format-check

  test-clj:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.469'

      - name: Cache maven
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('deps.edn') }}
          restore-keys: |
            m2-

      - name: Test
        run: ./script/test

  test-cljs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.469'

      - name: Cache maven
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('deps.edn') }}
          restore-keys: |
            m2-

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node_modules-

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: NPM Install
        run: npm install

      - name: Compile CLJS tests
        run: npx shadow-cljs compile ci

      - name: Run CLJS tests
        run: npx karma start --single-run
